'$schema' = 'https://starship.rs/config-schema.json'

continuation_prompt = 'â–¶â–¶'

[character]
success_symbol = '[âœ](bold green)'

[username]
style_user = 'bold green'
style_root = 'bold black'
format = '[$user]($style)@'
disabled = false
show_always = true

[directory]
style = 'bold blue'
home_symbol = 'ğŸ '

[git_status]
conflicted = 'ğŸš©'
untracked = 'âœ¨'
staged = '[++\($count\)](green)'

[time]
disabled = false
style = 'bold white'
